Alternative configuration
lowlighter/metrics pull request #1076
Opened 2022-05-25 17:10 UTC by LukasL28

Methode 1 is an alternative configuration, where you don't have to work with Github Tokens.

You can use {secrets.GITHUB_TOKEN} to automatically get the token. This is way more user friendly than the current described way.

2022-05-25 17:13 UTC, spenserblack requested changes
Just some spelling and spacing fixes.

2022-05-25 17:13 UTC, spenserblack commented on .github/readme/partials/documentation/setup/action.md
> +# Methode 2
```suggestion
# Method 2
```

2022-05-25 17:15 UTC, spenserblack commented
This brings something else up: perhaps in the section describing how to make a `METRICS_TOKEN`, it should be described why/when that token should be used.

2022-05-25 17:20 UTC, LukasL28 commented
> This brings something else up: in the section describing how to make a `METRICS_TOKEN`, perhaps it should be described why/when that token should be used.

Isn't it described in 2. ?

2022-05-25 17:51 UTC, closed without merging

2022-05-25 17:52 UTC, LukasL28 commented
There are Problems with that methode, if you use it for your profile Readme.md.

2022-05-25 18:05 UTC, spenserblack commented
>Isn't it described in 2. ?

Just something more explicit, like "You will need to create a custom token if..."

2022-05-29 00:22 UTC, lowlighter commented
I think you probably figured out but it's not possible to use `${{ github.token }}`/`${{ secrets.GITHUB_TOKEN }}` for `token` parameter. 

These auto-generated tokens are scoped to the current repository so they're not allowed to access and explore other GitHub data, which is required for all/most plugins. The `committer_token` does work with this though, since it push to said repository ( but this is already the default)

Thanks anyway for trying to improve metrics, I appreciate the effort 😄 !

2022-05-29 17:57 UTC, spenserblack commented
I think a lot of users of GitHub Actions are used to `github.token`/`secrets.GITHUB_TOKEN`, and some might assume that it's sufficient (it's good enough for a lot of other actions). It might be a good idea to describe to add something like this:
```
From the Developer settings of your account settings, select Personal access tokens to create a new token.
This token is required to query GitHub API data spanning multiple repositories.
```