fix: output of missing dependencies
lowlighter/metrics pull request #1077
Opened 2022-05-26 11:51 UTC by timokluser-dev

This PR fixes the dependency check outputs. 

On self hosted runners it seems like, that `jq` is not installed all the time. There is already a dependency check which runs before the main action and checks the runner. Unfortunately, the echo is not printing the name to console because when printing a variable, double quotes are needed.

Screenshot of running self hosted without `jq`:
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/57319535/170481160-e82cc66b-185b-4584-8e24-3e39f980a300.png">

I added the double quotes and escaped the existing ones.

2022-05-26 12:38 UTC, spenserblack commented
I believe the file you edited is generated, and `source/app/action/run.sh` is the actual file that needs to be changed.
https://github.com/lowlighter/metrics/blob/25d1410e45687c0f3000b5eb78446e0859fa18f7/.github/scripts/build.mjs#L80

2022-05-26 12:38 UTC, spenserblack requested changes
I believe the file you edited is generated, and `source/app/action/run.sh` is the actual file that needs to be changed.
https://github.com/lowlighter/metrics/blob/25d1410e45687c0f3000b5eb78446e0859fa18f7/.github/scripts/build.mjs#L80

2022-05-26 12:49 UTC, timokluser-dev commented
@spenserblack thanks for your comment 😄

2022-05-29 00:22 UTC, lowlighter approved these changes

2022-05-29 00:23 UTC, merged

2022-05-29 00:23 UTC, lowlighter commented
Thanks a lot for your contribution !